steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/shared-vpc-project-415009/test-repo/test-apache', './testfolder']
  id: 'Build docker image'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/shared-vpc-project-415009/test-repo/test-apache']
  id: 'Push docker image'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/testdeploy', 'my-image=us-docker.pkg.dev/shared-vpc-project-415009/test-repo/test-apache']  

options:
  logging: CLOUD_LOGGING_ONLY        
