 apiVersion: deploy.cloud.google.com/v1
 kind: DeliveryPipeline
 metadata: 
   name: test-delivery-pipeline
   labels:
     app: cicd
 description: this is to test cicd delivery pipeline
 serialPipeline:
   stages:
   - targetId: dev
